export type ThailandRegion = "North" | "Northeast" | "Central" | "East" | "West" | "South";

export type ProvinceMeta = {
  slug: string;
  province_name_th: string;
  province_name_en: string;
  region: ThailandRegion;
  latitude: number;
  longitude: number;
  population?: number;
  nearby_stations: string[];
};

export const THAILAND_PROVINCES: ProvinceMeta[] = [
  { slug: "amnat-charoen", province_name_th: "อำนาจเจริญ", province_name_en: "Amnat Charoen", region: "Northeast", latitude: 15.8657, longitude: 104.6258, nearby_stations: ["PCD", "Open-Meteo"] },
  { slug: "ang-thong", province_name_th: "อ่างทอง", province_name_en: "Ang Thong", region: "Central", latitude: 14.5896, longitude: 100.4551, nearby_stations: ["PCD", "Open-Meteo"] },
  { slug: "bangkok", province_name_th: "กรุงเทพมหานคร", province_name_en: "Bangkok", region: "Central", latitude: 13.7563, longitude: 100.5018, population: 5600000, nearby_stations: ["PCD", "OpenAQ", "Open-Meteo"] },
  { slug: "bueng-kan", province_name_th: "บึงกาฬ", province_name_en: "Bueng Kan", region: "Northeast", latitude: 18.3609, longitude: 103.6464, nearby_stations: ["Open-Meteo", "OpenAQ"] },
  { slug: "buriram", province_name_th: "บุรีรัมย์", province_name_en: "Buriram", region: "Northeast", latitude: 14.995, longitude: 103.1115, nearby_stations: ["PCD", "Open-Meteo"] },
  { slug: "chachoengsao", province_name_th: "ฉะเชิงเทรา", province_name_en: "Chachoengsao", region: "East", latitude: 13.6904, longitude: 101.0779, nearby_stations: ["PCD", "OpenAQ"] },
  { slug: "chai-nat", province_name_th: "ชัยนาท", province_name_en: "Chai Nat", region: "Central", latitude: 15.1852, longitude: 100.1251, nearby_stations: ["Open-Meteo"] },
  { slug: "chaiyaphum", province_name_th: "ชัยภูมิ", province_name_en: "Chaiyaphum", region: "Northeast", latitude: 15.8068, longitude: 102.0315, nearby_stations: ["Open-Meteo", "OpenAQ"] },
  { slug: "chanthaburi", province_name_th: "จันทบุรี", province_name_en: "Chanthaburi", region: "East", latitude: 12.6112, longitude: 102.1038, nearby_stations: ["Open-Meteo"] },
  { slug: "chiang-mai", province_name_th: "เชียงใหม่", province_name_en: "Chiang Mai", region: "North", latitude: 18.7883, longitude: 98.9853, nearby_stations: ["PCD", "OpenAQ", "Open-Meteo"] },
  { slug: "chiang-rai", province_name_th: "เชียงราย", province_name_en: "Chiang Rai", region: "North", latitude: 19.9105, longitude: 99.8406, nearby_stations: ["PCD", "OpenAQ", "Open-Meteo"] },
  { slug: "chonburi", province_name_th: "ชลบุรี", province_name_en: "Chonburi", region: "East", latitude: 13.3611, longitude: 100.9847, nearby_stations: ["PCD", "OpenAQ", "Open-Meteo"] },
  { slug: "chumphon", province_name_th: "ชุมพร", province_name_en: "Chumphon", region: "South", latitude: 10.493, longitude: 99.18, nearby_stations: ["Open-Meteo"] },
  { slug: "kalasin", province_name_th: "กาฬสินธุ์", province_name_en: "Kalasin", region: "Northeast", latitude: 16.4322, longitude: 103.5061, nearby_stations: ["Open-Meteo"] },
  { slug: "kamphaeng-phet", province_name_th: "กำแพงเพชร", province_name_en: "Kamphaeng Phet", region: "North", latitude: 16.4828, longitude: 99.5227, nearby_stations: ["Open-Meteo"] },
  { slug: "kanchanaburi", province_name_th: "กาญจนบุรี", province_name_en: "Kanchanaburi", region: "West", latitude: 14.0227, longitude: 99.5328, nearby_stations: ["PCD", "Open-Meteo"] },
  { slug: "khon-kaen", province_name_th: "ขอนแก่น", province_name_en: "Khon Kaen", region: "Northeast", latitude: 16.4419, longitude: 102.835, nearby_stations: ["PCD", "OpenAQ", "Open-Meteo"] },
  { slug: "krabi", province_name_th: "กระบี่", province_name_en: "Krabi", region: "South", latitude: 8.0863, longitude: 98.9063, nearby_stations: ["Open-Meteo"] },
  { slug: "lampang", province_name_th: "ลำปาง", province_name_en: "Lampang", region: "North", latitude: 18.2888, longitude: 99.4908, nearby_stations: ["PCD", "OpenAQ"] },
  { slug: "lamphun", province_name_th: "ลำพูน", province_name_en: "Lamphun", region: "North", latitude: 18.5743, longitude: 99.0087, nearby_stations: ["Open-Meteo"] },
  { slug: "loei", province_name_th: "เลย", province_name_en: "Loei", region: "Northeast", latitude: 17.486, longitude: 101.7223, nearby_stations: ["Open-Meteo"] },
  { slug: "lopburi", province_name_th: "ลพบุรี", province_name_en: "Lopburi", region: "Central", latitude: 14.7995, longitude: 100.6534, nearby_stations: ["PCD", "Open-Meteo"] },
  { slug: "mae-hong-son", province_name_th: "แม่ฮ่องสอน", province_name_en: "Mae Hong Son", region: "North", latitude: 19.2992, longitude: 97.9654, nearby_stations: ["Open-Meteo"] },
  { slug: "maha-sarakham", province_name_th: "มหาสารคาม", province_name_en: "Maha Sarakham", region: "Northeast", latitude: 16.1848, longitude: 103.3023, nearby_stations: ["Open-Meteo"] },
  { slug: "mukdahan", province_name_th: "มุกดาหาร", province_name_en: "Mukdahan", region: "Northeast", latitude: 16.5436, longitude: 104.72, nearby_stations: ["Open-Meteo"] },
  { slug: "nakhon-nayok", province_name_th: "นครนายก", province_name_en: "Nakhon Nayok", region: "Central", latitude: 14.2069, longitude: 101.2131, nearby_stations: ["Open-Meteo"] },
  { slug: "nakhon-pathom", province_name_th: "นครปฐม", province_name_en: "Nakhon Pathom", region: "Central", latitude: 13.8199, longitude: 100.0622, nearby_stations: ["PCD", "Open-Meteo"] },
  { slug: "nakhon-phanom", province_name_th: "นครพนม", province_name_en: "Nakhon Phanom", region: "Northeast", latitude: 17.392, longitude: 104.7696, nearby_stations: ["Open-Meteo"] },
  { slug: "nakhon-ratchasima", province_name_th: "นครราชสีมา", province_name_en: "Nakhon Ratchasima", region: "Northeast", latitude: 14.9799, longitude: 102.0977, nearby_stations: ["PCD", "OpenAQ", "Open-Meteo"] },
  { slug: "nakhon-sawan", province_name_th: "นครสวรรค์", province_name_en: "Nakhon Sawan", region: "Central", latitude: 15.7047, longitude: 100.1372, nearby_stations: ["PCD", "Open-Meteo"] },
  { slug: "nakhon-si-thammarat", province_name_th: "นครศรีธรรมราช", province_name_en: "Nakhon Si Thammarat", region: "South", latitude: 8.4304, longitude: 99.9631, nearby_stations: ["Open-Meteo"] },
  { slug: "nan", province_name_th: "น่าน", province_name_en: "Nan", region: "North", latitude: 18.7838, longitude: 100.7789, nearby_stations: ["Open-Meteo"] },
  { slug: "narathiwat", province_name_th: "นราธิวาส", province_name_en: "Narathiwat", region: "South", latitude: 6.4254, longitude: 101.8253, nearby_stations: ["Open-Meteo"] },
  { slug: "nong-bua-lamphu", province_name_th: "หนองบัวลำภู", province_name_en: "Nong Bua Lamphu", region: "Northeast", latitude: 17.2218, longitude: 102.426, nearby_stations: ["Open-Meteo"] },
  { slug: "nong-khai", province_name_th: "หนองคาย", province_name_en: "Nong Khai", region: "Northeast", latitude: 17.8783, longitude: 102.7413, nearby_stations: ["Open-Meteo"] },
  { slug: "nonthaburi", province_name_th: "นนทบุรี", province_name_en: "Nonthaburi", region: "Central", latitude: 13.8621, longitude: 100.5144, nearby_stations: ["PCD", "OpenAQ", "Open-Meteo"] },
  { slug: "pathum-thani", province_name_th: "ปทุมธานี", province_name_en: "Pathum Thani", region: "Central", latitude: 14.0208, longitude: 100.525, nearby_stations: ["PCD", "Open-Meteo"] },
  { slug: "pattani", province_name_th: "ปัตตานี", province_name_en: "Pattani", region: "South", latitude: 6.8695, longitude: 101.2505, nearby_stations: ["Open-Meteo"] },
  { slug: "phang-nga", province_name_th: "พังงา", province_name_en: "Phang Nga", region: "South", latitude: 8.4509, longitude: 98.5255, nearby_stations: ["Open-Meteo"] },
  { slug: "phatthalung", province_name_th: "พัทลุง", province_name_en: "Phatthalung", region: "South", latitude: 7.6167, longitude: 100.074, nearby_stations: ["Open-Meteo"] },
  { slug: "phayao", province_name_th: "พะเยา", province_name_en: "Phayao", region: "North", latitude: 19.1665, longitude: 99.9018, nearby_stations: ["Open-Meteo"] },
  { slug: "phetchabun", province_name_th: "เพชรบูรณ์", province_name_en: "Phetchabun", region: "North", latitude: 16.4189, longitude: 101.1557, nearby_stations: ["Open-Meteo"] },
  { slug: "phetchaburi", province_name_th: "เพชรบุรี", province_name_en: "Phetchaburi", region: "West", latitude: 13.1119, longitude: 99.9447, nearby_stations: ["Open-Meteo"] },
  { slug: "phichit", province_name_th: "พิจิตร", province_name_en: "Phichit", region: "North", latitude: 16.4419, longitude: 100.3482, nearby_stations: ["Open-Meteo"] },
  { slug: "phitsanulok", province_name_th: "พิษณุโลก", province_name_en: "Phitsanulok", region: "North", latitude: 16.8211, longitude: 100.2659, nearby_stations: ["PCD", "Open-Meteo"] },
  { slug: "phra-nakhon-si-ayutthaya", province_name_th: "พระนครศรีอยุธยา", province_name_en: "Phra Nakhon Si Ayutthaya", region: "Central", latitude: 14.3532, longitude: 100.5689, nearby_stations: ["PCD", "Open-Meteo"] },
  { slug: "phrae", province_name_th: "แพร่", province_name_en: "Phrae", region: "North", latitude: 18.1459, longitude: 100.141, nearby_stations: ["Open-Meteo"] },
  { slug: "phuket", province_name_th: "ภูเก็ต", province_name_en: "Phuket", region: "South", latitude: 7.8804, longitude: 98.3923, nearby_stations: ["PCD", "OpenAQ", "Open-Meteo"] },
  { slug: "prachin-buri", province_name_th: "ปราจีนบุรี", province_name_en: "Prachin Buri", region: "East", latitude: 14.0499, longitude: 101.3708, nearby_stations: ["Open-Meteo"] },
  { slug: "prachuap-khiri-khan", province_name_th: "ประจวบคีรีขันธ์", province_name_en: "Prachuap Khiri Khan", region: "West", latitude: 11.8124, longitude: 99.7973, nearby_stations: ["Open-Meteo"] },
  { slug: "ranong", province_name_th: "ระนอง", province_name_en: "Ranong", region: "South", latitude: 9.9529, longitude: 98.6085, nearby_stations: ["Open-Meteo"] },
  { slug: "ratchaburi", province_name_th: "ราชบุรี", province_name_en: "Ratchaburi", region: "West", latitude: 13.5283, longitude: 99.8134, nearby_stations: ["Open-Meteo"] },
  { slug: "rayong", province_name_th: "ระยอง", province_name_en: "Rayong", region: "East", latitude: 12.6814, longitude: 101.2816, nearby_stations: ["PCD", "OpenAQ", "Open-Meteo"] },
  { slug: "roi-et", province_name_th: "ร้อยเอ็ด", province_name_en: "Roi Et", region: "Northeast", latitude: 16.0567, longitude: 103.6531, nearby_stations: ["Open-Meteo"] },
  { slug: "sa-kaeo", province_name_th: "สระแก้ว", province_name_en: "Sa Kaeo", region: "East", latitude: 13.824, longitude: 102.0646, nearby_stations: ["Open-Meteo"] },
  { slug: "sakon-nakhon", province_name_th: "สกลนคร", province_name_en: "Sakon Nakhon", region: "Northeast", latitude: 17.1546, longitude: 104.1348, nearby_stations: ["Open-Meteo"] },
  { slug: "samut-prakan", province_name_th: "สมุทรปราการ", province_name_en: "Samut Prakan", region: "Central", latitude: 13.5991, longitude: 100.5998, nearby_stations: ["PCD", "OpenAQ", "Open-Meteo"] },
  { slug: "samut-sakhon", province_name_th: "สมุทรสาคร", province_name_en: "Samut Sakhon", region: "Central", latitude: 13.5475, longitude: 100.2744, nearby_stations: ["PCD", "Open-Meteo"] },
  { slug: "samut-songkhram", province_name_th: "สมุทรสงคราม", province_name_en: "Samut Songkhram", region: "Central", latitude: 13.4149, longitude: 100.0023, nearby_stations: ["Open-Meteo"] },
  { slug: "saraburi", province_name_th: "สระบุรี", province_name_en: "Saraburi", region: "Central", latitude: 14.5289, longitude: 100.9101, nearby_stations: ["PCD", "Open-Meteo"] },
  { slug: "satun", province_name_th: "สตูล", province_name_en: "Satun", region: "South", latitude: 6.6238, longitude: 100.066, nearby_stations: ["Open-Meteo"] },
  { slug: "sing-buri", province_name_th: "สิงห์บุรี", province_name_en: "Sing Buri", region: "Central", latitude: 14.8936, longitude: 100.3967, nearby_stations: ["Open-Meteo"] },
  { slug: "sisaket", province_name_th: "ศรีสะเกษ", province_name_en: "Sisaket", region: "Northeast", latitude: 15.1202, longitude: 104.3294, nearby_stations: ["Open-Meteo"] },
  { slug: "songkhla", province_name_th: "สงขลา", province_name_en: "Songkhla", region: "South", latitude: 7.1756, longitude: 100.6143, nearby_stations: ["PCD", "OpenAQ", "Open-Meteo"] },
  { slug: "sukhothai", province_name_th: "สุโขทัย", province_name_en: "Sukhothai", region: "North", latitude: 17.0056, longitude: 99.8264, nearby_stations: ["Open-Meteo"] },
  { slug: "suphan-buri", province_name_th: "สุพรรณบุรี", province_name_en: "Suphan Buri", region: "Central", latitude: 14.4742, longitude: 100.1177, nearby_stations: ["Open-Meteo"] },
  { slug: "surat-thani", province_name_th: "สุราษฎร์ธานี", province_name_en: "Surat Thani", region: "South", latitude: 9.1382, longitude: 99.3215, nearby_stations: ["PCD", "Open-Meteo"] },
  { slug: "surin", province_name_th: "สุรินทร์", province_name_en: "Surin", region: "Northeast", latitude: 14.8829, longitude: 103.4937, nearby_stations: ["Open-Meteo"] },
  { slug: "tak", province_name_th: "ตาก", province_name_en: "Tak", region: "West", latitude: 16.8839, longitude: 99.1258, nearby_stations: ["Open-Meteo"] },
  { slug: "trang", province_name_th: "ตรัง", province_name_en: "Trang", region: "South", latitude: 7.5563, longitude: 99.6114, nearby_stations: ["Open-Meteo"] },
  { slug: "trat", province_name_th: "ตราด", province_name_en: "Trat", region: "East", latitude: 12.2428, longitude: 102.517, nearby_stations: ["Open-Meteo"] },
  { slug: "ubon-ratchathani", province_name_th: "อุบลราชธานี", province_name_en: "Ubon Ratchathani", region: "Northeast", latitude: 15.2448, longitude: 104.8473, nearby_stations: ["PCD", "OpenAQ", "Open-Meteo"] },
  { slug: "udon-thani", province_name_th: "อุดรธานี", province_name_en: "Udon Thani", region: "Northeast", latitude: 17.4157, longitude: 102.7859, nearby_stations: ["PCD", "OpenAQ", "Open-Meteo"] },
  { slug: "uthai-thani", province_name_th: "อุทัยธานี", province_name_en: "Uthai Thani", region: "Central", latitude: 15.3794, longitude: 100.0246, nearby_stations: ["Open-Meteo"] },
  { slug: "uttaradit", province_name_th: "อุตรดิตถ์", province_name_en: "Uttaradit", region: "North", latitude: 17.6201, longitude: 100.0993, nearby_stations: ["Open-Meteo"] },
  { slug: "yala", province_name_th: "ยะลา", province_name_en: "Yala", region: "South", latitude: 6.5411, longitude: 101.2804, nearby_stations: ["Open-Meteo"] },
  { slug: "yasothon", province_name_th: "ยโสธร", province_name_en: "Yasothon", region: "Northeast", latitude: 15.7926, longitude: 104.1453, nearby_stations: ["Open-Meteo"] },
];

export const THAILAND_PROVINCE_MAP = Object.fromEntries(THAILAND_PROVINCES.map((p) => [p.slug, p]));
