-- Compact forecast-vintage features for direct D+1..D+7 PM2.5 models.
--
-- One row is retained per province/origin business date/target date.  Raw
-- provider payloads, hourly grids and satellite rasters deliberately stay out
-- of Postgres so the contract remains suitable for the Supabase Free plan.

create table if not exists public.forecast_covariates_daily (
  id bigint generated by default as identity primary key,
  province_id varchar(5) not null
    references public.isan_provinces(province_id),
  forecast_origin timestamptz not null,
  origin_date date not null,
  target_date date not null,
  forecast_horizon_days smallint not null,
  forecast_temp_mean real,
  forecast_humidity_mean real,
  forecast_wind_speed_mean real,
  forecast_wind_u_mean real,
  forecast_wind_v_mean real,
  forecast_precip_total real,
  forecast_pblh_mean real,
  cams_pm25_mean real,
  cams_aod_mean real,
  cams_dust_mean real,
  weather_hours smallint not null default 0,
  air_quality_hours smallint not null default 0,
  source text not null,
  missingness jsonb not null default '{}'::jsonb,
  provenance jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint forecast_covariates_daily_horizon_check
    check (forecast_horizon_days between 1 and 7),
  constraint forecast_covariates_daily_target_check
    check (target_date = origin_date + forecast_horizon_days::integer),
  constraint forecast_covariates_daily_weather_hours_check
    check (weather_hours between 0 and 25),
  constraint forecast_covariates_daily_air_hours_check
    check (air_quality_hours between 0 and 25),
  unique (province_id, origin_date, target_date, source)
);

create index if not exists idx_forecast_covariates_target
  on public.forecast_covariates_daily
  (province_id, target_date, forecast_origin desc);

create index if not exists idx_forecast_covariates_origin
  on public.forecast_covariates_daily
  (origin_date desc, forecast_horizon_days, province_id);

alter table public.forecast_covariates_daily enable row level security;

revoke all privileges on table public.forecast_covariates_daily
  from public, anon, authenticated;
grant select, insert, update, delete on table public.forecast_covariates_daily
  to service_role;
grant usage, select on sequence public.forecast_covariates_daily_id_seq
  to service_role;

comment on table public.forecast_covariates_daily is
  'Daily province-level forecast vintages for leakage-safe direct D+1..D+7 PM2.5 training and inference. Raw provider grids are excluded.';

